### ISSUE TITLE
Support request creates an email body containing HPC job information

### ISSUE THREAD

**Issue by ndjones** [nesi/agdr-docs#20]
Need to update the email request to suit AGDR, as currently it has templated content about HPC job submission.

https://github.com/nesi/agdr-docs/blob/74edf8db2619b85d9db1865966b7ad15209e8aec/overrides/partials/nav_support_request.html#L2

**Comment by natnesi** [comment]
thank you. Fixed in the latest commit https://github.com/nesi/agdr-docs/commit/d1f33903913df7ba1f01d9a48d5b20da8ce65d06
https://github.com/nesi/agdr-docs/actions/runs/9072573620
